package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Actiontype generated by hbm2java
 */
@Entity
@Table(name = "actiontype", catalog = "remotemeter")
public class Actiontype implements java.io.Serializable {

	private Integer pid;
	private String actionName;
	private Set<Useractionlog> useractionlogs = new HashSet<Useractionlog>(0);

	public Actiontype() {
	}

	public Actiontype(String actionName) {
		this.actionName = actionName;
	}

	public Actiontype(String actionName, Set<Useractionlog> useractionlogs) {
		this.actionName = actionName;
		this.useractionlogs = useractionlogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "ActionName", nullable = false, length = 20)
	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actiontype")
	public Set<Useractionlog> getUseractionlogs() {
		return this.useractionlogs;
	}

	public void setUseractionlogs(Set<Useractionlog> useractionlogs) {
		this.useractionlogs = useractionlogs;
	}

}
