package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Where;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "authority", catalog = "remotemeter")
public class Authority implements java.io.Serializable {

	private Integer pid;
	private Integer ppid;//父级权限,根权限菜单该值为0
	private String authorityCode;//权限编码配置国际化
	private String actUrl;//操作路径 host port之后的路径
	private char valid;
	private String remark;
	private Authority au;
	private Set<Authority> aus;//子集菜单
	@OneToMany(targetEntity = Authority.class)
	@JoinColumn(name="PPID",insertable=false,updatable = false)
	public Set<Authority> getAus() {
		return aus;
	}

	public void setAus(Set<Authority> aus) {
		this.aus = aus;
	}

	@OneToOne(targetEntity = Authority.class)
	@JoinColumn(name="PPID",insertable=false,updatable = false,nullable = true)
	@Where(clause="valid='1' ")
	public Authority getAu() {
		return au;
	}

	public void setAu(Authority au) {
		this.au = au;
	}

	public Authority() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}
	@Column(name = "Valid", nullable = false, length = 1)
	public char getValid() {
		return this.valid;
	}
	@Column(name = "PPID")
	public Integer getPpid() {
		return ppid;
	}

	public void setPpid(Integer ppid) {
		this.ppid = ppid;
	}
	@Column(name = "AuthorityCode")
	public String getAuthorityCode() {
		return authorityCode;
	}

	public void setAuthorityCode(String authorityCode) {
		this.authorityCode = authorityCode;
	}
	@Column(name = "ActUrl")
	public String getActUrl() {
		return actUrl;
	}

	public void setActUrl(String actUrl) {
		this.actUrl = actUrl;
	}

	public void setValid(char valid) {
		this.valid = valid;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
}
