package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "authority", catalog = "remotemeter")
public class Authority implements java.io.Serializable {

	private Integer pid;
	private String authorityName;
	private char valid;
	private String remark;
	private Set<RoleAuthority> roleAuthorities = new HashSet<RoleAuthority>(0);

	public Authority() {
	}

	public Authority(String authorityName, char valid) {
		this.authorityName = authorityName;
		this.valid = valid;
	}

	public Authority(String authorityName, char valid, String remark,
			Set<RoleAuthority> roleAuthorities) {
		this.authorityName = authorityName;
		this.valid = valid;
		this.remark = remark;
		this.roleAuthorities = roleAuthorities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "AuthorityName", nullable = false, length = 20)
	public String getAuthorityName() {
		return this.authorityName;
	}

	public void setAuthorityName(String authorityName) {
		this.authorityName = authorityName;
	}

	@Column(name = "Valid", nullable = false, length = 1)
	public char getValid() {
		return this.valid;
	}

	public void setValid(char valid) {
		this.valid = valid;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authority")
	public Set<RoleAuthority> getRoleAuthorities() {
		return this.roleAuthorities;
	}

	public void setRoleAuthorities(Set<RoleAuthority> roleAuthorities) {
		this.roleAuthorities = roleAuthorities;
	}

}
