package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Basicprice generated by hbm2java
 */
@Entity
@Table(name = "basicprice", catalog = "remotemeter")
public class Basicprice implements java.io.Serializable {

	private Integer pid;
	private Pricekind pricekind;
	private String basicPriceName;
	private BigDecimal basicPriceFirst;
	private int basicFirstOver;
	private BigDecimal basicPriceSecond;
	private int basicSecondOver;
	private BigDecimal basicPriceThird;
	private int perYL;
	private String valid;
	private String remark;

	public Basicprice() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PriceKindID", nullable = false)
	public Pricekind getPricekind() {
		return this.pricekind;
	}

	public void setPricekind(Pricekind pricekind) {
		this.pricekind = pricekind;
	}

	@Column(name = "BasicPriceName", nullable = false, length = 20)
	public String getBasicPriceName() {
		return this.basicPriceName;
	}

	public void setBasicPriceName(String basicPriceName) {
		this.basicPriceName = basicPriceName;
	}

	@Column(name = "BasicPriceFirst", nullable = false, scale = 4)
	public BigDecimal getBasicPriceFirst() {
		return this.basicPriceFirst;
	}

	public void setBasicPriceFirst(BigDecimal basicPriceFirst) {
		this.basicPriceFirst = basicPriceFirst;
	}

	@Column(name = "BasicFirstOver", nullable = false)
	public int getBasicFirstOver() {
		return this.basicFirstOver;
	}

	public void setBasicFirstOver(int basicFirstOver) {
		this.basicFirstOver = basicFirstOver;
	}

	@Column(name = "BasicPriceSecond", nullable = false, scale = 4)
	public BigDecimal getBasicPriceSecond() {
		return this.basicPriceSecond;
	}

	public void setBasicPriceSecond(BigDecimal basicPriceSecond) {
		this.basicPriceSecond = basicPriceSecond;
	}

	@Column(name = "BasicSecondOver", nullable = false)
	public int getBasicSecondOver() {
		return this.basicSecondOver;
	}

	public void setBasicSecondOver(int basicSecondOver) {
		this.basicSecondOver = basicSecondOver;
	}

	@Column(name = "BasicPriceThird", nullable = false, scale = 4)
	public BigDecimal getBasicPriceThird() {
		return this.basicPriceThird;
	}

	public void setBasicPriceThird(BigDecimal basicPriceThird) {
		this.basicPriceThird = basicPriceThird;
	}

	@Column(name = "Valid", nullable = false, length = 5)
	public String getValid() {
		return this.valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "perYL", nullable = false)
	public int getPerYL() {
		return perYL;
	}

	public void setPerYL(int perYL) {
		this.perYL = perYL;
	}

}
