package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customerpaylog generated by hbm2java
 */
@Entity
@Table(name = "customerpaylog", catalog = "remotemeter")
public class Customerpaylog implements java.io.Serializable {

	private Integer pid;
	private Customer customer;
	private Admininfo admininfo;
	private BigDecimal amount;
	private Date actionTime;
	private byte prePaySign;
	private String valid;
	private String remark;

	public Customerpaylog() {
	}

	public Customerpaylog(Customer customer, Admininfo admininfo,
			BigDecimal amount, Date actionTime, byte prePaySign, String valid) {
		this.customer = customer;
		this.admininfo = admininfo;
		this.amount = amount;
		this.actionTime = actionTime;
		this.prePaySign = prePaySign;
		this.valid = valid;
	}

	public Customerpaylog(Customer customer, Admininfo admininfo,
			BigDecimal amount, Date actionTime, byte prePaySign, String valid,
			String remark) {
		this.customer = customer;
		this.admininfo = admininfo;
		this.amount = amount;
		this.actionTime = actionTime;
		this.prePaySign = prePaySign;
		this.valid = valid;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AdminID", nullable = false)
	public Admininfo getAdmininfo() {
		return this.admininfo;
	}

	public void setAdmininfo(Admininfo admininfo) {
		this.admininfo = admininfo;
	}

	@Column(name = "Amount", nullable = false, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActionTime", nullable = false, length = 19)
	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	@Column(name = "PrePaySign", nullable = false)
	public byte getPrePaySign() {
		return this.prePaySign;
	}

	public void setPrePaySign(byte prePaySign) {
		this.prePaySign = prePaySign;
	}

	@Column(name = "Valid", nullable = false, length = 1)
	public String getValid() {
		return this.valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
