package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Housekind generated by hbm2java
 */
@Entity
@Table(name = "housekind", catalog = "remotemeter")
public class Housekind implements java.io.Serializable {

	private Integer pid;
	private String hkname;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Housekind() {
	}

	public Housekind(String hkname) {
		this.hkname = hkname;
	}

	public Housekind(String hkname, Set<Customer> customers) {
		this.hkname = hkname;
		this.customers = customers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "HKName", nullable = false, length = 20)
	public String getHkname() {
		return this.hkname;
	}

	public void setHkname(String hkname) {
		this.hkname = hkname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "housekind")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
