package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Meterkind generated by hbm2java
 */
@Entity
@Table(name = "meterkind", catalog = "remotemeter")
public class Meterkind implements java.io.Serializable {

	private Integer pid;
	private String meterTypeName;
	private String meterMm;
	private int remote;
	private Integer handStyle;
	private char valid;
	private String remark;
	private Set<Meter> meters = new HashSet<Meter>(0);

	public Meterkind() {
	}

	public Meterkind(String meterMm, int remote, char valid) {
		this.meterMm = meterMm;
		this.remote = remote;
		this.valid = valid;
	}

	public Meterkind(String meterTypeName, String meterMm, int remote,
			Integer handStyle, char valid, String remark, Set<Meter> meters) {
		this.meterTypeName = meterTypeName;
		this.meterMm = meterMm;
		this.remote = remote;
		this.handStyle = handStyle;
		this.valid = valid;
		this.remark = remark;
		this.meters = meters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "MeterTypeName", length = 20)
	public String getMeterTypeName() {
		return this.meterTypeName;
	}

	public void setMeterTypeName(String meterTypeName) {
		this.meterTypeName = meterTypeName;
	}

	@Column(name = "MeterMM", nullable = false, length = 10)
	public String getMeterMm() {
		return this.meterMm;
	}

	public void setMeterMm(String meterMm) {
		this.meterMm = meterMm;
	}

	@Column(name = "Remote", nullable = false)
	public int getRemote() {
		return this.remote;
	}

	public void setRemote(int remote) {
		this.remote = remote;
	}

	@Column(name = "HandStyle")
	public Integer getHandStyle() {
		return this.handStyle;
	}

	public void setHandStyle(Integer handStyle) {
		this.handStyle = handStyle;
	}

	@Column(name = "Valid", nullable = false, length = 1)
	public char getValid() {
		return this.valid;
	}

	public void setValid(char valid) {
		this.valid = valid;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "meterkind")
	public Set<Meter> getMeters() {
		return this.meters;
	}

	public void setMeters(Set<Meter> meters) {
		this.meters = meters;
	}

}
