package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Meter generated by hbm2java
 */
@Entity
@Table(name = "meter", catalog = "remotemeter")
public class Meter implements java.io.Serializable {

	private Integer pid;
	private Pricekind pricekind;
	private Neighbor neighbor;
	private Customer customer;
	private Gprs gprs;
	private Meterkind meterkind;
	private String apid;
	private String steelNum;
	private String qfh;
	private String collectorAddr;
	private String meterAddr;
	private byte meterSolid;
	private char lihu;
	private int mainMeter;
	private int suppleMode;
	private int isValve;
	private Byte valveState;
	private Integer deductionStyle;
	private Integer valveOffthre;
	private Byte meterState;
	private Integer deRead;
	private Date deTime;
	private int timerSwitch;
	private String timer;
	private Integer overflow;
	private Integer changend;
	private Integer changestart;
	private Integer readdata;
	private Date readtime;
	private char valid;
	private String remark;
	private Set<Readmeterlog> readmeterlogs = new HashSet<Readmeterlog>(0);
	private Set<Meterdeductionlog> meterdeductionlogs = new HashSet<Meterdeductionlog>(
			0);
	private Set<Valveconflog> valveconflogs = new HashSet<Valveconflog>(0);

	public Meter() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PriceKindID", nullable = false)
	public Pricekind getPricekind() {
		return this.pricekind;
	}

	public void setPricekind(Pricekind pricekind) {
		this.pricekind = pricekind;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NeighborID", nullable = false)
	public Neighbor getNeighbor() {
		return neighbor;
	}

	public void setNeighbor(Neighbor neighbor) {
		this.neighbor = neighbor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GPRSID")
	public Gprs getGprs() {
		return this.gprs;
	}

	public void setGprs(Gprs gprs) {
		this.gprs = gprs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MeterKindID", nullable = false)
	public Meterkind getMeterkind() {
		return this.meterkind;
	}

	public void setMeterkind(Meterkind meterkind) {
		this.meterkind = meterkind;
	}

	@Column(name = "APID", length = 20)
	public String getApid() {
		return this.apid;
	}

	public void setApid(String apid) {
		this.apid = apid;
	}

	@Column(name = "SteelNum", nullable = false, length = 20)
	public String getSteelNum() {
		return this.steelNum;
	}

	public void setSteelNum(String steelNum) {
		this.steelNum = steelNum;
	}

	@Column(name = "qfh", length = 20)
	public String getQfh() {
		return this.qfh;
	}

	public void setQfh(String qfh) {
		this.qfh = qfh;
	}

	@Column(name = "CollectorAddr", nullable = false, length = 20)
	public String getCollectorAddr() {
		return this.collectorAddr;
	}

	public void setCollectorAddr(String collectorAddr) {
		this.collectorAddr = collectorAddr;
	}

	@Column(name = "MeterAddr", nullable = false, length = 20)
	public String getMeterAddr() {
		return this.meterAddr;
	}

	public void setMeterAddr(String meterAddr) {
		this.meterAddr = meterAddr;
	}

	@Column(name = "MeterSolid", nullable = false)
	public byte getMeterSolid() {
		return this.meterSolid;
	}

	public void setMeterSolid(byte meterSolid) {
		this.meterSolid = meterSolid;
	}

	@Column(name = "Lihu", nullable = false, length = 1)
	public char getLihu() {
		return this.lihu;
	}

	public void setLihu(char lihu) {
		this.lihu = lihu;
	}

	@Column(name = "MainMeter", nullable = false)
	public int getMainMeter() {
		return this.mainMeter;
	}

	public void setMainMeter(int mainMeter) {
		this.mainMeter = mainMeter;
	}

	@Column(name = "SuppleMode", nullable = false)
	public int getSuppleMode() {
		return this.suppleMode;
	}

	public void setSuppleMode(int suppleMode) {
		this.suppleMode = suppleMode;
	}

	@Column(name = "IsValve", nullable = false)
	public int getIsValve() {
		return this.isValve;
	}

	public void setIsValve(int isValve) {
		this.isValve = isValve;
	}

	@Column(name = "ValveState")
	public Byte getValveState() {
		return this.valveState;
	}

	public void setValveState(Byte valveState) {
		this.valveState = valveState;
	}

	@Column(name = "DeductionStyle")
	public Integer getDeductionStyle() {
		return this.deductionStyle;
	}

	public void setDeductionStyle(Integer deductionStyle) {
		this.deductionStyle = deductionStyle;
	}

	@Column(name = "ValveOFFThre")
	public Integer getValveOffthre() {
		return this.valveOffthre;
	}

	public void setValveOffthre(Integer valveOffthre) {
		this.valveOffthre = valveOffthre;
	}

	@Column(name = "MeterState")
	public Byte getMeterState() {
		return this.meterState;
	}

	public void setMeterState(Byte meterState) {
		this.meterState = meterState;
	}

	@Column(name = "DeRead")
	public Integer getDeRead() {
		return this.deRead;
	}

	public void setDeRead(Integer deRead) {
		this.deRead = deRead;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeTime", length = 19)
	public Date getDeTime() {
		return this.deTime;
	}

	public void setDeTime(Date deTime) {
		this.deTime = deTime;
	}

	@Column(name = "TimerSwitch", nullable = false)
	public int getTimerSwitch() {
		return this.timerSwitch;
	}

	public void setTimerSwitch(int timerSwitch) {
		this.timerSwitch = timerSwitch;
	}

	@Column(name = "Timer", length = 20)
	public String getTimer() {
		return this.timer;
	}

	public void setTimer(String timer) {
		this.timer = timer;
	}

	@Column(name = "Overflow")
	public Integer getOverflow() {
		return this.overflow;
	}

	public void setOverflow(Integer overflow) {
		this.overflow = overflow;
	}
	
	@Column(name = "changend")
	public Integer getChangend() {
		return changend;
	}

	public void setChangend(Integer changend) {
		this.changend = changend;
	}
	
	@Column(name = "changestart")
	public Integer getChangestart() {
		return changestart;
	}

	public void setChangestart(Integer changestart) {
		this.changestart = changestart;
	}
	@Column(name = "readdata")
	public Integer getReaddata() {
		return readdata;
	}

	public void setReaddata(Integer readdata) {
		this.readdata = readdata;
	}
	@Column(name = "readtime")
	public Date getReadtime() {
		return readtime;
	}

	public void setReadtime(Date readtime) {
		this.readtime = readtime;
	}

	@Column(name = "Valid", nullable = false, length = 1)
	public char getValid() {
		return this.valid;
	}

	public void setValid(char valid) {
		this.valid = valid;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "meter")
	public Set<Readmeterlog> getReadmeterlogs() {
		return this.readmeterlogs;
	}

	public void setReadmeterlogs(Set<Readmeterlog> readmeterlogs) {
		this.readmeterlogs = readmeterlogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "meter")
	public Set<Meterdeductionlog> getMeterdeductionlogs() {
		return this.meterdeductionlogs;
	}

	public void setMeterdeductionlogs(Set<Meterdeductionlog> meterdeductionlogs) {
		this.meterdeductionlogs = meterdeductionlogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "meter")
	public Set<Valveconflog> getValveconflogs() {
		return this.valveconflogs;
	}

	public void setValveconflogs(Set<Valveconflog> valveconflogs) {
		this.valveconflogs = valveconflogs;
	}

}
