package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pricekind generated by hbm2java
 */
@Entity
@Table(name = "pricekind", catalog = "remotemeter")
public class Pricekind implements java.io.Serializable {

	private Integer pid;
	private Watercompany watercompany;
	private String priceKindName;
	private double priceKindFine;
	private String valid;
	private String remark;
	//private Set<Meterdeductionlog> meterdeductionlogs = new HashSet<Meterdeductionlog>(
	//		0);
	private Set<Basicprice> basicprices = new HashSet<Basicprice>(0);
	//private Set<Meter> meters = new HashSet<Meter>(0);

	public Pricekind() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WCID", nullable = false)
	public Watercompany getWatercompany() {
		return this.watercompany;
	}

	public void setWatercompany(Watercompany watercompany) {
		this.watercompany = watercompany;
	}

	@Column(name = "PriceKindName", nullable = false, length = 20)
	public String getPriceKindName() {
		return this.priceKindName;
	}

	public void setPriceKindName(String priceKindName) {
		this.priceKindName = priceKindName;
	}

	@Column(name = "PriceKindFine", nullable = false, precision = 24)
	public double getPriceKindFine() {
		return this.priceKindFine;
	}

	public void setPriceKindFine(double priceKindFine) {
		this.priceKindFine = priceKindFine;
	}

	@Column(name = "Valid", nullable = false, length = 1)
	public String getValid() {
		return this.valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "pricekind")
	public Set<Meterdeductionlog> getMeterdeductionlogs() {
		return this.meterdeductionlogs;
	}

	public void setMeterdeductionlogs(Set<Meterdeductionlog> meterdeductionlogs) {
		this.meterdeductionlogs = meterdeductionlogs;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pricekind")
	public Set<Basicprice> getBasicprices() {
		return this.basicprices;
	}

	public void setBasicprices(Set<Basicprice> basicprices) {
		this.basicprices = basicprices;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pricekind")
	public Set<Meter> getMeters() {
		return this.meters;
	}

	public void setMeters(Set<Meter> meters) {
		this.meters = meters;
	}*/

}
