package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Propertyresp generated by hbm2java
 */
@Entity
@Table(name = "propertyresp", catalog = "remotemeter")
public class Propertyresp implements java.io.Serializable {

	private Integer pid;
	private Neighbor neighbor;
	private String respName;
	private String respTel;
	private String respMobile;
	private String respEmail;
	private String respAddr;
	private char valid;
	private String remark;

	public Propertyresp() {
	}

	public Propertyresp(Neighbor neighbor, char valid) {
		this.neighbor = neighbor;
		this.valid = valid;
	}

	public Propertyresp(Neighbor neighbor, String respName, String respTel,
			String respMobile, String respEmail, String respAddr, char valid,
			String remark) {
		this.neighbor = neighbor;
		this.respName = respName;
		this.respTel = respTel;
		this.respMobile = respMobile;
		this.respEmail = respEmail;
		this.respAddr = respAddr;
		this.valid = valid;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NeighborID", nullable = false)
	public Neighbor getNeighbor() {
		return this.neighbor;
	}

	public void setNeighbor(Neighbor neighbor) {
		this.neighbor = neighbor;
	}

	@Column(name = "RespName", length = 20)
	public String getRespName() {
		return this.respName;
	}

	public void setRespName(String respName) {
		this.respName = respName;
	}

	@Column(name = "RespTel", length = 12)
	public String getRespTel() {
		return this.respTel;
	}

	public void setRespTel(String respTel) {
		this.respTel = respTel;
	}

	@Column(name = "RespMobile", length = 20)
	public String getRespMobile() {
		return this.respMobile;
	}

	public void setRespMobile(String respMobile) {
		this.respMobile = respMobile;
	}

	@Column(name = "RespEmail", length = 80)
	public String getRespEmail() {
		return this.respEmail;
	}

	public void setRespEmail(String respEmail) {
		this.respEmail = respEmail;
	}

	@Column(name = "RespAddr", length = 80)
	public String getRespAddr() {
		return this.respAddr;
	}

	public void setRespAddr(String respAddr) {
		this.respAddr = respAddr;
	}

	@Column(name = "Valid", nullable = false, length = 1)
	public char getValid() {
		return this.valid;
	}

	public void setValid(char valid) {
		this.valid = valid;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
