package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Readmeterlog generated by hbm2java
 */
@Entity
@Table(name = "readmeterlog", catalog = "remotemeter")
public class Readmeterlog implements java.io.Serializable {

	private Integer pid;
	private Meter meter;
	private Readlog readlog;
	private byte actionType;
	private Date actionTime;
	private int actionResult;
	private String remark;

	public Readmeterlog() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MeterID", nullable = false)
	public Meter getMeter() {
		return this.meter;
	}

	public void setMeter(Meter meter) {
		this.meter = meter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ReadLogID", nullable = false)
	public Readlog getReadlog() {
		return this.readlog;
	}

	public void setReadlog(Readlog readlog) {
		this.readlog = readlog;
	}

	@Column(name = "ActionType", nullable = false)
	public byte getActionType() {
		return this.actionType;
	}

	public void setActionType(byte actionType) {
		this.actionType = actionType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActionTime", nullable = false, length = 19)
	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	@Column(name = "ActionResult", nullable = false)
	public int getActionResult() {
		return this.actionResult;
	}

	public void setActionResult(int actionResult) {
		this.actionResult = actionResult;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
