package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Useractionlog generated by hbm2java
 */
@Entity
@Table(name = "useractionlog", catalog = "remotemeter")
public class Useractionlog implements java.io.Serializable {

	private Integer pid;
	private Actiontype actiontype;
	private Admininfo admininfo;
	private Integer targerId;
	private Date actionTime;
	private String remark;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ActionType", nullable = false)
	public Actiontype getActiontype() {
		return this.actiontype;
	}

	public void setActiontype(Actiontype actiontype) {
		this.actiontype = actiontype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AdminID", nullable = false)
	public Admininfo getAdmininfo() {
		return this.admininfo;
	}

	public void setAdmininfo(Admininfo admininfo) {
		this.admininfo = admininfo;
	}

	@Column(name = "TargerID")
	public Integer getTargerId() {
		return this.targerId;
	}

	public void setTargerId(Integer targerId) {
		this.targerId = targerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActionTime", nullable = false, length = 19)
	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	@Column(name = "Remark", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
