package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Valvelog generated by hbm2java
 */
@Entity
@Table(name = "valvelog", catalog = "remotemeter")
public class Valvelog implements java.io.Serializable {

	private Integer pid;
	private Admininfo admininfo;
	private Date actionTime;
	private int auto;
	private int actionCount;
	private int completeCount;
	private int errorCount;
	private int status;
	private String failReason;
	private String remark;
	private Set<Valveconflog> valveconflogs = new HashSet<Valveconflog>(0);

	public Valvelog() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AdminID", nullable = false)
	public Admininfo getAdmininfo() {
		return this.admininfo;
	}

	public void setAdmininfo(Admininfo admininfo) {
		this.admininfo = admininfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActionTime", length = 19)
	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	@Column(name = "Auto", nullable = false)
	public int getAuto() {
		return this.auto;
	}

	public void setAuto(int auto) {
		this.auto = auto;
	}

	@Column(name = "ActionCount", nullable = false)
	public int getActionCount() {
		return this.actionCount;
	}

	public void setActionCount(int actionCount) {
		this.actionCount = actionCount;
	}

	@Column(name = "CompleteCount", nullable = false)
	public int getCompleteCount() {
		return this.completeCount;
	}

	public void setCompleteCount(int completeCount) {
		this.completeCount = completeCount;
	}

	@Column(name = "ErrorCount", nullable = false)
	public int getErrorCount() {
		return this.errorCount;
	}

	public void setErrorCount(int errorCount) {
		this.errorCount = errorCount;
	}

	@Column(name = "Status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "FailReason", length = 65535)
	public String getFailReason() {
		return this.failReason;
	}

	public void setFailReason(String failReason) {
		this.failReason = failReason;
	}

	@Column(name = "Remark", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "valvelog")
	public Set<Valveconflog> getValveconflogs() {
		return this.valveconflogs;
	}

	public void setValveconflogs(Set<Valveconflog> valveconflogs) {
		this.valveconflogs = valveconflogs;
	}

}
