package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Valveconflog generated by hbm2java
 */
@Entity
@Table(name = "valveconflog", catalog = "remotemeter")
public class Valveconflog implements java.io.Serializable {

	private Integer pid;
	private Meter meter;
	private Valvelog valvelog;
	private int switch_;
	private int result;
	private String errorReason;
	private Integer errorStatus;
	private String removeReason;
	private Date completeTime;

	public Valveconflog() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MeterID")
	public Meter getMeter() {
		return this.meter;
	}

	public void setMeter(Meter meter) {
		this.meter = meter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ValveLogID", nullable = false)
	public Valvelog getValvelog() {
		return this.valvelog;
	}

	public void setValvelog(Valvelog valvelog) {
		this.valvelog = valvelog;
	}

	@Column(name = "Switch", nullable = false)
	public int getSwitch_() {
		return this.switch_;
	}

	public void setSwitch_(int switch_) {
		this.switch_ = switch_;
	}

	@Column(name = "Result", nullable = false)
	public int getResult() {
		return this.result;
	}

	public void setResult(int result) {
		this.result = result;
	}

	@Column(name = "ErrorReason", length = 65535)
	public String getErrorReason() {
		return this.errorReason;
	}

	public void setErrorReason(String errorReason) {
		this.errorReason = errorReason;
	}

	@Column(name = "ErrorStatus")
	public Integer getErrorStatus() {
		return this.errorStatus;
	}

	public void setErrorStatus(Integer errorStatus) {
		this.errorStatus = errorStatus;
	}

	@Column(name = "RemoveReason", length = 65535)
	public String getRemoveReason() {
		return this.removeReason;
	}

	public void setRemoveReason(String removeReason) {
		this.removeReason = removeReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CompleteTime", length = 19)
	public Date getCompleteTime() {
		return this.completeTime;
	}

	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

}
