package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Warnlog generated by hbm2java
 */
@Entity
@Table(name = "warnlog", catalog = "remotemeter")
public class Warnlog implements java.io.Serializable {

	private Integer pid;
	private Customer customer;
	private int warnStyle;
	private String mobile;
	private String email;
	private String warnContent;
	private String warnReason;
	private Date actionTime;
	private int warnCount;
	private Integer successCount;
	private Integer failCount;
	private char valid;
	private int warn;

	public Warnlog() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerID", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "WarnStyle", nullable = false)
	public int getWarnStyle() {
		return this.warnStyle;
	}

	public void setWarnStyle(int warnStyle) {
		this.warnStyle = warnStyle;
	}

	@Column(name = "Mobile", length = 11)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "Email", length = 80)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "WarnContent", length = 200)
	public String getWarnContent() {
		return this.warnContent;
	}

	public void setWarnContent(String warnContent) {
		this.warnContent = warnContent;
	}

	@Column(name = "WarnReason", length = 200)
	public String getWarnReason() {
		return this.warnReason;
	}

	public void setWarnReason(String warnReason) {
		this.warnReason = warnReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActionTime", nullable = false, length = 19)
	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	@Column(name = "WarnCount", nullable = false)
	public int getWarnCount() {
		return this.warnCount;
	}

	public void setWarnCount(int warnCount) {
		this.warnCount = warnCount;
	}

	@Column(name = "SuccessCount")
	public Integer getSuccessCount() {
		return this.successCount;
	}

	public void setSuccessCount(Integer successCount) {
		this.successCount = successCount;
	}

	@Column(name = "FailCount")
	public Integer getFailCount() {
		return this.failCount;
	}

	public void setFailCount(Integer failCount) {
		this.failCount = failCount;
	}

	@Column(name = "Valid", nullable = false, length = 1)
	public char getValid() {
		return this.valid;
	}

	public void setValid(char valid) {
		this.valid = valid;
	}

	@Column(name = "Warn", nullable = false)
	public int getWarn() {
		return this.warn;
	}

	public void setWarn(int warn) {
		this.warn = warn;
	}

}
