package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wastelog generated by hbm2java
 */
@Entity
@Table(name = "wastelog", catalog = "remotemeter")
public class Wastelog implements java.io.Serializable {

	private Integer pid;
	private Neighbor neighbor;
	private int readLogId;
	private int meterid;
	private Date actionTime;
	private int waste;
	private char valid;
	private String remark;

	public Wastelog() {
	}

	public Wastelog(Neighbor neighbor, int readLogId, int meterid, int waste,
			char valid) {
		this.neighbor = neighbor;
		this.readLogId = readLogId;
		this.meterid = meterid;
		this.waste = waste;
		this.valid = valid;
	}

	public Wastelog(Neighbor neighbor, int readLogId, int meterid,
			Date actionTime, int waste, char valid, String remark) {
		this.neighbor = neighbor;
		this.readLogId = readLogId;
		this.meterid = meterid;
		this.actionTime = actionTime;
		this.waste = waste;
		this.valid = valid;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Neighborid", nullable = false)
	public Neighbor getNeighbor() {
		return this.neighbor;
	}

	public void setNeighbor(Neighbor neighbor) {
		this.neighbor = neighbor;
	}

	@Column(name = "ReadLogID", nullable = false)
	public int getReadLogId() {
		return this.readLogId;
	}

	public void setReadLogId(int readLogId) {
		this.readLogId = readLogId;
	}

	@Column(name = "Meterid", nullable = false)
	public int getMeterid() {
		return this.meterid;
	}

	public void setMeterid(int meterid) {
		this.meterid = meterid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ActionTime", length = 19)
	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	@Column(name = "Waste", nullable = false)
	public int getWaste() {
		return this.waste;
	}

	public void setWaste(int waste) {
		this.waste = waste;
	}

	@Column(name = "Valid", nullable = false, length = 1)
	public char getValid() {
		return this.valid;
	}

	public void setValid(char valid) {
		this.valid = valid;
	}

	@Column(name = "Remark", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
