package com.xdkj.yccb.main.entity;

// Generated 2015-3-6 17:30:45 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Watercompany generated by hbm2java
 */
@Entity
@Table(name = "watercompany", catalog = "remotemeter")
public class Watercompany implements java.io.Serializable {

	private Integer pid;
	private String companyName;
	private String companyAddr;
	private String mark;
	private int authority;
	private String remark;
	private Set<Roles> roleses = new HashSet<Roles>(0);
	private Set<Neighbor> neighbors = new HashSet<Neighbor>(0);
	private Set<Pricekind> pricekinds = new HashSet<Pricekind>(0);
	private Set<Admininfo> admininfos = new HashSet<Admininfo>(0);
	private Set<Department> departments = new HashSet<Department>(0);

	public Watercompany() {
	}
	
	public Watercompany(Integer pid) {
		this.pid=pid;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PID", unique = true, nullable = false)
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "CompanyName", nullable = false, length = 80)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "CompanyAddr", length = 80)
	public String getCompanyAddr() {
		return this.companyAddr;
	}

	public void setCompanyAddr(String companyAddr) {
		this.companyAddr = companyAddr;
	}

	@Column(name = "Mark", nullable = false, length = 4)
	public String getMark() {
		return this.mark;
	}

	public void setMark(String mark) {
		this.mark = mark;
	}

	@Column(name = "Authority", nullable = false)
	public int getAuthority() {
		return this.authority;
	}

	public void setAuthority(int authority) {
		this.authority = authority;
	}

	@Column(name = "Remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "watercompany")
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "watercompany")
	public Set<Neighbor> getNeighbors() {
		return this.neighbors;
	}

	public void setNeighbors(Set<Neighbor> neighbors) {
		this.neighbors = neighbors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "watercompany")
	public Set<Pricekind> getPricekinds() {
		return this.pricekinds;
	}

	public void setPricekinds(Set<Pricekind> pricekinds) {
		this.pricekinds = pricekinds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "watercompany")
	public Set<Admininfo> getAdmininfos() {
		return this.admininfos;
	}

	public void setAdmininfos(Set<Admininfo> admininfos) {
		this.admininfos = admininfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "watercompany")
	public Set<Department> getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set<Department> departments) {
		this.departments = departments;
	}

}
